# Generated by Django 5.0.1 on 2024-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_owner', models.CharField(max_length=32, verbose_name='order owner name')),
                ('owner_num', models.IntegerField(verbose_name='number of total passengers')),
                ('location', models.CharField(max_length=256, verbose_name='location')),
                ('destination', models.CharField(max_length=256, verbose_name='destination')),
                ('date', models.TextField(verbose_name='date')),
                ('time', models.TextField(verbose_name='time')),
                ('time_earlist', models.TextField(verbose_name='earliest acceptable arrival time')),
                ('time_latest', models.TextField(verbose_name='latest acceptable arrival time')),
                ('driver', models.CharField(blank=True, max_length=32, null=True, verbose_name='driver name')),
                ('vehicle_type', models.TextField(default='', verbose_name='vehicle type')),
                ('seats_num', models.IntegerField(default=0, verbose_name='number of seats in vehicle')),
                ('is_share', models.BooleanField(default=False, verbose_name='whether to share')),
                ('share_user', models.CharField(blank=True, max_length=32, null=True, verbose_name='share user name')),
                ('share_num', models.IntegerField(blank=True, null=True, verbose_name='shared number of total passengers')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='whether has been confirmed')),
                ('status', models.CharField(default='open', verbose_name='ride status')),
                ('info', models.TextField(blank=True, default='None', null=True, verbose_name='special vehicle info')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('is_driver', models.IntegerField(default=0, verbose_name='driver status')),
                ('vehicle_type', models.TextField(default='', verbose_name='vehicle type')),
                ('driver_license', models.IntegerField(default=0, verbose_name='driver license')),
                ('seats_num', models.IntegerField(default=0, verbose_name='maximum number of passengers')),
                ('special_info', models.TextField(default='', verbose_name='special vehicle info')),
            ],
        ),
    ]
